//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("UFSoft.UBF.Exceptions", ClrNamespace = "UFSoft.UBF.Exceptions")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.datacontract.org/2004/07/UFSoft.UBF.Exceptions", ClrNamespace = "UFSoft.UBF.Exceptions")]

namespace UFSoft.UBF
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    public partial class ExceptionBase : System.Exception
    {

        public ExceptionBase(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name = "ExceptionBase.FormatState", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
        public enum FormatState : uint
        {

            [System.Runtime.Serialization.EnumMemberAttribute()]
            None = 0,

            [System.Runtime.Serialization.EnumMemberAttribute()]
            Formatting = 1,

            [System.Runtime.Serialization.EnumMemberAttribute()]
            Formatted = 2,
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class UnknownException : UFSoft.UBF.ExceptionBase
    {

        public UnknownException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorMessage", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private UFSoft.UBF.ErrorDescriptor errDescriptorField;

        private string errorTypeField;

        private UFSoft.UBF.ErrorMessage[] innerMessagesField;

        private string messageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public UFSoft.UBF.ErrorDescriptor errDescriptor
        {
            get
            {
                return this.errDescriptorField;
            }
            set
            {
                this.errDescriptorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string errorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ErrorMessage[] innerMessages
        {
            get
            {
                return this.innerMessagesField;
            }
            set
            {
                this.innerMessagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorDescriptor", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public partial class ErrorDescriptor : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string categoryField;

        private string erroridField;

        private UFSoft.UBF.ErrorLevel levelField;

        private string ownerField;

        private System.DateTime timeStampField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string errorid
        {
            get
            {
                return this.erroridField;
            }
            set
            {
                this.erroridField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ErrorLevel level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorLevel", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")]
    public enum ErrorLevel : short
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warn = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fatal = 4,
    }
}
namespace UFSoft.UBF.Business
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    public partial class BusinessException : UFSoft.UBF.ExceptionBase
    {

        public BusinessException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class AttrsContainerException : UFSoft.UBF.Business.BusinessException
    {

        public AttrsContainerException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class AttributeInValidException : UFSoft.UBF.Business.BusinessException
    {

        public AttributeInValidException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class EntityNotExistException : UFSoft.UBF.Business.BusinessException
    {

        public EntityNotExistException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }
}
namespace UFSoft.UBF.Service
{
    using System;
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class ServiceException : UFSoft.UBF.ExceptionBase
    {

        public ServiceException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    public partial class ServiceLostException : UFSoft.UBF.ExceptionBase
    {

        public ServiceLostException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) :
            base(info, context)
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceExceptionDetail", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")]
    public partial class ServiceExceptionDetail : System.ServiceModel.ExceptionDetail, System.Runtime.Serialization.IExtensibleDataObject
    {
        private ServiceExceptionDetail(Exception _ex)
            : base(_ex)
        {

        }

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private UFSoft.UBF.ExceptionBase ExceptionField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.ExceptionBase Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Util.Context
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ApplicationContext", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ApplicationContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Collections.Generic.Dictionary<object, object> nameValueHasField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.Dictionary<object, object> nameValueHas
        {
            get
            {
                return this.nameValueHasField;
            }
            set
            {
                this.nameValueHasField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PlatformContext", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.ServiceModel.ExceptionDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ApplicationContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Util.Context.ThreadContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBase[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ExceptionBase.FormatState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.UnknownException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorDescriptor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.ErrorMessage[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBaseFormatState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Exceptions.MessageBaseFormatState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.BusinessException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttrsContainerException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.AttributeInValidException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Business.EntityNotExistException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceLostException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFSoft.UBF.Service.ServiceExceptionDetail))]
    public partial class PlatformContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private object ctxField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public object ctx
        {
            get
            {
                return this.ctxField;
            }
            set
            {
                this.ctxField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ThreadContext", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Util.Context")]
    public partial class ThreadContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Collections.Generic.Dictionary<object, object> nameValueHasField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.Dictionary<object, object> nameValueHas
        {
            get
            {
                return this.nameValueHasField;
            }
            set
            {
                this.nameValueHasField = value;
            }
        }
    }
}
namespace UFSoft.UBF.Exceptions
{
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageBase.FormatState", Namespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Exceptions")]
    public enum MessageBaseFormatState : uint
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formatting = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Formatted = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageBase", Namespace = "UFSoft.UBF.Exceptions")]
    public partial class MessageBase : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string attributeMetadataIDField;

        private string attributeNameField;

        private string entityFullNameField;

        private long entityIDField;

        private string entityMetadataIDField;

        private short errorLevelField;

        private UFSoft.UBF.Exceptions.MessageBaseFormatState formatedField;

        private UFSoft.UBF.Exceptions.MessageBase[] innerMessagesField;

        private bool isValidEntityIDField;

        private string localMessageField;

        private string orginalEntityFullNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attributeMetadataID
        {
            get
            {
                return this.attributeMetadataIDField;
            }
            set
            {
                this.attributeMetadataIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entityFullName
        {
            get
            {
                return this.entityFullNameField;
            }
            set
            {
                this.entityFullNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long entityID
        {
            get
            {
                return this.entityIDField;
            }
            set
            {
                this.entityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entityMetadataID
        {
            get
            {
                return this.entityMetadataIDField;
            }
            set
            {
                this.entityMetadataIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short errorLevel
        {
            get
            {
                return this.errorLevelField;
            }
            set
            {
                this.errorLevelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Exceptions.MessageBaseFormatState formated
        {
            get
            {
                return this.formatedField;
            }
            set
            {
                this.formatedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFSoft.UBF.Exceptions.MessageBase[] innerMessages
        {
            get
            {
                return this.innerMessagesField;
            }
            set
            {
                this.innerMessagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isValidEntityID
        {
            get
            {
                return this.isValidEntityIDField;
            }
            set
            {
                this.isValidEntityIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localMessage
        {
            get
            {
                return this.localMessageField;
            }
            set
            {
                this.localMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orginalEntityFullName
        {
            get
            {
                return this.orginalEntityFullNameField;
            }
            set
            {
                this.orginalEntityFullNameField = value;
            }
        }
    }
}
